# Generated by Django 4.2.17 on 2025-01-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('employee', 'Employee')], default='client', max_length=10),
        ),
    ]
