# Generated by Django 5.1.5 on 2025-01-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('employee', 'Employee'), ('admin', 'Admin')], default='client', max_length=10),
        ),
    ]
